export type DefaultMotoboyNeighborhood = {
  id: string;
  neighborhoodName: string;
  city: string;
  price: number;
  sortOrder: number;
};

function cityNeighborhoods(
  cityCode: string,
  city: string,
  entries: Array<[string, number]>,
): DefaultMotoboyNeighborhood[] {
  return entries.map(([neighborhoodName, price], index) => ({
    id: `seed_motoboy_${cityCode}_${String(index + 1).padStart(3, "0")}`,
    neighborhoodName,
    city,
    price,
    sortOrder: index + 1,
  }));
}

export const DEFAULT_MOTOBOY_NEIGHBORHOODS: DefaultMotoboyNeighborhood[] = [
  ...cityNeighborhoods("sa", "Santo André", [
    ["Centro", 70],
    ["Vila Assunção", 70],
    ["Campestre", 70],
    ["Paraíso", 70],
    ["Vila Gilda", 75],
    ["Santa Terezinha", 75],
    ["Bangu", 75],
    ["Parque das Nações", 75],
    ["Jardim do Estádio", 75],
    ["Vila Luzita", 80],
    ["Jardim Belval", 80],
    ["Vila Valparaíso", 80],
    ["Parque Erasmo Assunção", 80],
    ["Jardim Santo Alberto", 80],
    ["Jd. Ana Maria", 80],
    ["Sítio dos Vianas", 80],
    ["Vila Pires", 80],
    ["Parque Capuava", 85],
    ["Vila Palmares", 85],
    ["Jardim Alvorada", 85],
    ["Parque Miami", 85],
    ["Jd. Cristianópolis", 85],
    ["Jd. do Estádio", 85],
    ["Vila Curuçá", 85],
    ["Jardim Ipanema", 85],
    ["Jardim Utinga", 85],
    ["Jardim Alvorada", 90],
    ["Jardim Santo André", 90],
    ["Parque Jaçatuba", 90],
    ["Recanto da Natureza", 90],
    ["Rio Grande da Serra (divisa)", 90],
  ]),
  ...cityNeighborhoods("sbc", "São Bernardo do Campo", [
    ["Rudge Ramos", 75],
    ["Anchieta", 75],
    ["Jardim do Mar", 80],
    ["Centro", 80],
    ["Baeta Neves", 80],
    ["Nova Petrópolis", 85],
    ["Assunção", 85],
    ["Planalto", 90],
    ["Demarchi", 90],
    ["Ferrazópolis", 90],
    ["Alves Dias", 95],
    ["Dos Casa", 95],
    ["Cooperativa", 100],
    ["Alvarenga", 100],
    ["Montanhão", 105],
    ["Tatetos", 105],
    ["Batistini", 110],
    ["Pós-Balsa / Divisa", 110],
  ]),
  ...cityNeighborhoods("sp", "São Paulo", [
    ["Água Rasa", 60],
    ["Aricanduva", 70],
    ["Artur Alvim", 75],
    ["Alto de Pinheiros", 65],
    ["Anhanguera", 90],
    ["Barra Funda", 50],
    ["Bela Vista", 50],
    ["Bom Retiro", 50],
    ["Brás", 50],
    ["Belém", 50],
    ["Brasilândia", 80],
    ["Butantã", 75],
    ["Consolação", 50],
    ["Casa Verde", 60],
    ["Cangaíba", 75],
    ["Carrão", 70],
    ["Cidade Líder", 75],
    ["Cidade Tiradentes", 90],
    ["Cambuci", 50],
    ["Campo Belo", 65],
    ["Campo Grande", 75],
    ["Campo Limpo", 80],
    ["Capão Redondo", 80],
    ["Cidade Ademar", 75],
    ["Cidade Dutra", 80],
    ["Cursino", 65],
    ["Cachoeirinha", 75],
    ["Ermelino Matarazzo", 75],
    ["Freguesia do Ó", 70],
    ["Guaianases", 90],
    ["Grajaú", 90],
    ["Iguatemi", 90],
    ["Itaim Paulista", 90],
    ["Itaquera", 80],
    ["Ipiranga", 60],
    ["Itaim Bibi", 65],
    ["Jaçanã", 80],
    ["Jardim Helena", 90],
    ["José Bonifácio", 85],
    ["Jabaquara", 65],
    ["Jardim Ângela", 80],
    ["Jardim Paulista", 65],
    ["Jardim São Luís", 80],
    ["Jaguara", 80],
    ["Jaguaré", 80],
    ["Jaraguá", 80],
    ["Liberdade", 50],
    ["Lajeado", 90],
    ["Lapa", 70],
    ["Limão", 70],
    ["Mandaqui", 75],
    ["Mooca", 50],
    ["Marsilac", 100],
    ["Moema", 65],
    ["Morumbi", 70],
    ["Pari", 50],
    ["Parque do Carmo", 80],
    ["Penha", 70],
    ["Ponte Rasa", 75],
    ["Parelheiros", 95],
    ["Pedreira", 80],
    ["Perdizes", 65],
    ["Perus", 90],
    ["Pinheiros", 65],
    ["Pirituba", 80],
    ["República", 50],
    ["Raposo Tavares", 80],
    ["Rio Pequeno", 75],
    ["Santa Cecília", 50],
    ["Sé", 50],
    ["Sapopemba", 75],
    ["São Lucas", 70],
    ["São Mateus", 80],
    ["São Miguel", 85],
    ["São Rafael", 85],
    ["Sacomã", 65],
    ["Santo Amaro", 70],
    ["Saúde", 65],
    ["Socorro", 75],
    ["São Domingos", 80],
    ["Tremembé", 90],
    ["Tucuruvi", 75],
    ["Tatuapé", 65],
    ["Vila Guilherme", 60],
    ["Vila Maria", 65],
    ["Vila Medeiros", 70],
    ["Vila Curuçá", 90],
    ["Vila Formosa", 70],
    ["Vila Jacuí", 80],
    ["Vila Matilde", 70],
    ["Vila Prudente", 60],
    ["Vila Andrade", 75],
    ["Vila Mariana", 60],
    ["Vila Leopoldina", 80],
  ]),
];
