import { Router, type IRouter } from "express";
import healthRouter from "./health";
import productsRouter from "./products";
import pixRouter from "./pix";
import ordersRouter from "./orders";
import adminAuthRouter from "./admin-auth";
import notificationsRouter from "./notifications";
import customChargesRouter from "./custom-charges";
import webhooksRouter from "./webhooks";
import couponsRouter from "./coupons";
import settingsRouter from "./settings";
import sellersRouter from "./sellers";
import shippingOptionsRouter from "./shipping-options";
import motoboyNeighborhoodsRouter from "./motoboy-neighborhoods";
import motoboyCepRangesRouter from "./motoboy-cep-ranges";
import orderBumpsRouter from "./order-bumps";
import checkoutRouter from "./checkout";
import kycRouter from "./kyc";
import socialProofRouter from "./social-proof";
import trackingRouter from "./tracking";
import customerAuthRouter from "./customer-auth";
import affiliateRouter from "./affiliate";
import sellerCommissionPaymentsRouter from "./seller-commission-payments";
import rafflesRouter from "./raffles";
import financialSummaryRouter from "./financial-summary";
import marketingExpensesRouter from "./marketing-expenses";
import supportRouter from "./support";
import reshipmentsRouter from "./reshipments";
import clientErrorsRouter from "./client-errors";
import tenantsRouter from "./tenants";
import filialPurchasesRouter from "./filial-purchases";

import brevoRouter from "./brevo";
const router: IRouter = Router();

router.use(healthRouter);
router.use(productsRouter);
router.use(pixRouter);
router.use(ordersRouter);
router.use(adminAuthRouter);
router.use(notificationsRouter);
router.use(customChargesRouter);
router.use(webhooksRouter);
router.use(couponsRouter);
router.use(settingsRouter);
router.use(sellersRouter);
router.use(shippingOptionsRouter);
router.use(motoboyNeighborhoodsRouter);
router.use(motoboyCepRangesRouter);
router.use(orderBumpsRouter);
router.use(checkoutRouter);
router.use(kycRouter);
router.use(socialProofRouter);
router.use(financialSummaryRouter);
router.use(marketingExpensesRouter);
router.use(trackingRouter);
router.use(customerAuthRouter);
router.use(affiliateRouter);
router.use(sellerCommissionPaymentsRouter);
router.use(rafflesRouter);
router.use(supportRouter);
router.use(reshipmentsRouter);
router.use(clientErrorsRouter);
router.use(tenantsRouter);
router.use(filialPurchasesRouter);
router.use(brevoRouter);

export default router;
